"""aver

Revision ID: 2daff3d41760
Revises: 5a64b1d2c75e
Create Date: 2024-12-03 22:53:00.291544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2daff3d41760'
down_revision = '5a64b1d2c75e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
