"""relacion

Revision ID: 4281959360a0
Revises: bb139abc0036
Create Date: 2024-12-03 22:41:15.836038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4281959360a0'
down_revision = 'bb139abc0036'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
