"""ultima chancee

Revision ID: 44140a4eaab7
Revises: 2daff3d41760
Create Date: 2024-12-03 23:16:16.974526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44140a4eaab7'
down_revision = '2daff3d41760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
