"""a ver

Revision ID: 5a64b1d2c75e
Revises: d5e86854071e
Create Date: 2024-12-03 22:51:27.054434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a64b1d2c75e'
down_revision = 'd5e86854071e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
